version: "3"
services:
  drivenops_database_test:
    image: postgres
    container_name: drivenops_database_test
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  drivenops_back_test:
    container_name: drivenops_back_test
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - drivenops_database_test