version: "3"
services:
  drivenops_database:
    image: postgres
    container_name: drivenops_database
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres:/var/lib/postgresql/data
  drivenops_back_app:
    container_name: drivenops_back_app
    build: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - drivenops_database
    env_file:
      - ./back-end/.env
  drivenops_front_app:
    build: ./front-end
    container_name: drivenops_front_app
    env_file:
      - ./front-end/.env
    volumes: 
      - build_react:/var/www/html
  nginx:
    build: ./nginx
    container_name: nginx
    ports: 
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - drivenops_front_app
      - drivenops_back_app
      - drivenops_database
volumes:
  build_react:
  postgres: